---
- name: Configuration avancée du serveur web Nginx sur Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour du cache des paquets
      apt:
        update_cache: yes

    - name: Installation de Nginx
      apt:
        name: nginx
        state: present

    - name: Copie du fichier de configuration du site
      template:
        src: /chemin/vers/votre/template/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        remote_src: false  # Spécifie que le fichier existe sur l'hôte distant
      notify: Reload Nginx

    - name: Démarrage de Nginx et configuration pour le démarrage automatique
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
