---
- name: Configuration avancée du serveur web
  hosts: all
  become: yes
  tasks:
    - name: Installer Nginx
      yum:
        name: nginx
        state: present

    - name: Copier le fichier de configuration du site
      template:
        src: /chemin/vers/votre/template/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Reload Nginx

    - name: Démarrer Nginx et le configurer pour le démarrage automatique
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
